/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nuvem_tags;

import java.awt.Dimension;
import javax.swing.JFrame;

/**
 *
 * @author pedrogoncalves
 */
public class NewApplet extends java.applet.Applet {

    /**
     * Initializes the applet NewApplet
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                     JFrame janela = new NewJFrame();
      
      // http://www.devdaily.com/java/java-set-jframe-size
      janela.setPreferredSize(new Dimension(500, 500));
      janela.pack();
      janela.setVisible(true);
        
                    
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
